sudo: required

language: node_js
before_install:
  - docker pull dsva/healthcare-application:build-cached
  - docker images
install: docker build -t travis-image -f Dockerfile.travis .
env:
  global:
    - DOCKER_EMAIL=awong.dev@gmail.com
    - DOCKER_USERNAME=awongdev
    - secure: nyOcp09Xzs9RhOF7wqRGk5yJ8e+NVXGaJVr79LvzrknZAHKrB3QMptC/rECGKTKdrwHr7Jas6/+mK36ZpIVUEF1P3EdDrsCYd6Vrgk+NS4UlgEBzCz5qnxaeLp1RA4BZ2pUVXQyavlQnRGgODiqw4C9aI4VKyaiz4QaskDH9fra/Sz8afmkwoSl0jKXn0kl+DstMrP71rJHZ31eznLC6d2AW8Y/LcA+7Abi5yq9ltDwK9h6RUB4VlTNJiis6xPyegw8OmIKIMpsnfeQpbf2oYpodxp4zLtJlr5RdXXli2zQ67mibtt/0+1dqsNQpxIdT9NU9ZucM1bBuiCbTJfd+7IURJkhz+4AU+vzenH9RNvYu5zqS/ykIhQGSi4L2QPWHJ1u++D97seJQ5BMUl85ZejdmVVhauV0AwPvrBplnZGHw6k9fuc5PZWHQGDLKynt/Jo/kHePLvbxTPGpYa+eU/uCRzdmxtJU0UBQucaj+S3Ub0mwyFpfYyOmED03AhNvodZVmLnx9EKfOq1t33+cnRYpAvvmWH0X0xtNC/HTfaBAwsrapr9mwFaZV4zIHVWqo9o70/HEvTe1/PQ0iC/N1FeKRxJ34cxTs4hUVE027wJc07jqyMs5tbn4fj2cLJXav3jGoKnS/lR9FKVl2VMoNhxr+/lMmykXTiBQ84noroww=
    - secure: 2hEWgre+knhjAUKzmzYVHEnE+vo71/10EaSxrJXBDuJQFpsWOdQKg3OFuvbqF5McoLbxyknm2xJEHXuheOnZ/LHLcRsqywWq8zNPwSf5lYVGsLvPe3EclX7V2kONmkR/PlUwDbsqgnIx8qPM9pWNXmTrmgwZd7RirpemeiSBSBoWCcMbxqx4QUXRqdnkI1P5BDBlN9wOItbOza2IA3LzsPGI5drV4gZZO9wWt/8GCMV1SvACpWF5CWPdNoF9crpEwaLHJwY1AJsjHRGSHMWN+hCK81He9zFYIIv2LM/jDAU7UWlwB9r7WYgdqABOdEroGRpPPf6jWN6cpcDUCBYZesz5SgR33RWYUvqf0RaATwen9DOHi+BcFukDExNU8x7INsHKCH74ILrbjhiODy/orSvavsElW9okpCZOdl6dlDuTCnzbk2EC7p8iDB/XcenI12VcY8lAezhi+iGlY2uPjpasIVMSdomcGUy+9zDC83GD16YgTEGL4RVbMvudYCQ8j9WT+ocYU3+XoAsvQ70OZA9Chy9TNliDiOJMwdAvw74M80d52YOLKZ7fkBbIAgHCk2YB7dXRo8MEDWFyA7/6Ps/32FN+QEL5cqqXtWlkuYnijX/gKhh2LTLSLnuHYGVuKCIJ6ORqESib042o1tK6P0v9M8u9BvCNaUV2EjY4yPs= # SAUCE_ACCESS_KEY
    - secure: FLho25KV6HmLRHQUAjBqmJOR2xWr0qqCHPmOywfNHdnpxN9l/dX32kcTcw8reDXex5w44T7KE1K9le0peqTxOvPnu4zBNyCuRroiwje2408FYR5AsDh03qiPKm9yUnGUUAsVSugG0Lwj8ePdpyY2ulfUrZvpZ84oTjDf+XEI9S/Vk0oQhxgZCo356m1MYyUjOnwGQGyH5JWwwEedh8imO2zatquBT+RwTvqFlzzwarI7EsGpQTxs09KCv9JTisT/VttMBNr/tDC7ZKcuu8Rl8hYrmp60P0diAfMaYuR7PunB2vn894527eIjn3ISnUqpnnFrRBkHg7PlE565H+T/bQHXB8TCboT0AmgiIOybjOo8MbVOpXG6wrPgWpczYVftfoZ0oBj2xrouW59sJ/TeyeauUGocDJCYIx2LGGKDOT6/YegWf7Tgo+25RzjhaxpsSk3dJoyveRi5W1z9WMKzsxsX+aXQDmYRy4o1DyVSLKiZPkyqRb18yPaxxiohteXuEsC9lLE9QnHRr2xn91S9+8GR6+NGY4WXx7T1wpDpFyVd1WrUzYHe2jFyOhBzJzMubqa+cwl5qaDgHsNUk+cngpZK3JT9ASji6CqNasNcclBamDM0rMDLx4dsMhQCeuGx4BFQpw6J0XIvi1cNInMWX4PEDYzhV3lP+lstrjKJgYg= # SAUCE_USERNAME
services:
  - docker
script:
  - docker run --rm -p 9876:9876 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e TRAVIS_JOB_NUMBER -it travis-image npm test
  - docker run --rm -p 3000:3000 -e SAUCE_USERNAME -e SAUCE_ACCESS_KEY -e TRAVIS_JOB_NUMBER -it travis-image scripts/e2e-tests.sh
addons:
  sauce_connect:
    username: awong-usds
    access_key:
      secure: 2hEWgre+knhjAUKzmzYVHEnE+vo71/10EaSxrJXBDuJQFpsWOdQKg3OFuvbqF5McoLbxyknm2xJEHXuheOnZ/LHLcRsqywWq8zNPwSf5lYVGsLvPe3EclX7V2kONmkR/PlUwDbsqgnIx8qPM9pWNXmTrmgwZd7RirpemeiSBSBoWCcMbxqx4QUXRqdnkI1P5BDBlN9wOItbOza2IA3LzsPGI5drV4gZZO9wWt/8GCMV1SvACpWF5CWPdNoF9crpEwaLHJwY1AJsjHRGSHMWN+hCK81He9zFYIIv2LM/jDAU7UWlwB9r7WYgdqABOdEroGRpPPf6jWN6cpcDUCBYZesz5SgR33RWYUvqf0RaATwen9DOHi+BcFukDExNU8x7INsHKCH74ILrbjhiODy/orSvavsElW9okpCZOdl6dlDuTCnzbk2EC7p8iDB/XcenI12VcY8lAezhi+iGlY2uPjpasIVMSdomcGUy+9zDC83GD16YgTEGL4RVbMvudYCQ8j9WT+ocYU3+XoAsvQ70OZA9Chy9TNliDiOJMwdAvw74M80d52YOLKZ7fkBbIAgHCk2YB7dXRo8MEDWFyA7/6Ps/32FN+QEL5cqqXtWlkuYnijX/gKhh2LTLSLnuHYGVuKCIJ6ORqESib042o1tK6P0v9M8u9BvCNaUV2EjY4yPs=

notifications:
  email: false
# TODO(awong): Breaking dev deployments temporariliy until docker-based CI is stable again.
#deploy:
#  provider: script
#  script: ./scripts/release-docker.sh
#  skip_cleanup: true
#  on:
#    branch: master
